# Generated by Django 3.2.3 on 2021-05-19 02:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='primeiro nome')),
                ('surname', models.CharField(max_length=15, verbose_name='sobrenome nome')),
                ('rg', models.CharField(max_length=10, verbose_name='documento de rg')),
                ('cpf', models.CharField(max_length=20, verbose_name='documento de cpf')),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome do curso')),
                ('cod_curso', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediario'), ('A', 'Avançado')], default='B', max_length=1)),
            ],
        ),
    ]
