# Generated by Django 3.2.4 on 2021-06-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matriculas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='Number Phone')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('-phone',),
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='contacts',
            field=models.ManyToManyField(related_name='alunos_contatos', to='escola.Contacts'),
        ),
    ]
